server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://localhost:8085/hello
        predicates:
        - After=2018-04-20T17:42:47.789-07:00[America/Denver]

spring:
  cloud:
    gateway:
      routes:
      - id: before_route
        uri: http://localhost:8085/hello
        predicates:
        - Before=2018-04-20T17:42:47.789-07:00[America/Denver

spring:
  cloud:
    gateway:
      routes:
      - id: between_route
        uri: http://localhost:8085/hello
        predicates:
        - Between=2018-04-20T17:42:47.789-07:00[America/Denver],2019-04-20T17:42:47.789-07:00[America/Denver]

spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: http://localhost:8085/hello
        predicates:
        - Cookie=name,test

spring:
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: http://localhost:8085/hello
        predicates:
        - Header=X-Request-Id,\d+

spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://localhost:8085/hello
        predicates:
        - Host=**.baidu.org

spring:
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: http://localhost:8085/hello
        predicates:
        - Method=GET

spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://localhost:8085/hello
        predicates:
        - Path=/test/{name}

spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: http://localhost:8085/hello
        predicates:
        - Query=name,test.

spring:
  cloud:
    gateway:
      routes:
      - id: remoteaddr_route
        uri: http://localhost:8085/hello
        predicates:
        - RemoteAddr=192.168.1.1