server:
    port: 8081

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost2:8082/eureka/

spring:
    application:
        name: eurka-server
